### ISSUE TITLE
Issue 1: Can View Favorites And Library

### ISSUE THREAD

**Issue by CollinHovey** [CollinHovey/my-shiny-entries#1]
## ⚙️ Feature

> ##### User can view their favorite shinies and their library of shinies

## 📐 Plan

> ##### Summary of the technical approach to be taken.

Create a carousel for the Favorites to scroll through all of the favorited items
Create a Library that is a list of all the shinies that have been added

## 🖼️ Wireframes

> ##### Update
wireframe(s) of what the app should look like when the updates are ready.

![chrome_EFJyJvTdTs](https://user-images.githubusercontent.com/102557430/173662982-771ccd9d-fc3d-48f0-9f59-3a0625f00424.png)
![chrome_dHvtYdUtLV](https://user-images.githubusercontent.com/102557430/173662989-23a4a08c-1210-4769-8d42-be418538d9d2.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the CSS for Favorites Tab
- [x] Create the CSS for the Library Tab
- [x] Can Switch views between the two tabs
- [x] Make Carousel for Favorite tab
- [x] make search bar for favorites tab
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that don't do anything.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
