### ISSUE TITLE
Issue 2: User Can Add A New Shiny

### ISSUE THREAD

**Issue by CollinHovey** [CollinHovey/my-shiny-entries#2]
## ⚙️ Feature

> ##### User Can Add a New Shiny  

## 📐 Plan

> ##### Summary of the technical approach to be taken.

Create Functionality for New Catch button to add a new entry to library

## 🖼️ Wireframes

> ##### Updated wireframe(s) of what the app should look like when the updates are ready.

![chrome_3m9ZGvtnAs](https://user-images.githubusercontent.com/102557430/173668413-f16cce9d-7a98-4d8f-a64f-d83b662cabdb.png)
![chrome_5xvz98QUND](https://user-images.githubusercontent.com/102557430/173668420-2d6cca39-8f96-4aaa-88ac-9859fa6503e4.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Clicking New Catch Brings up the New Catch Tab
- [ ] New catch tab has inputs for Pokemon, Pokemon NickName, and Encounters
- [ ] New catch tab has save and cancel buttons
- [ ] cancel returns you to library
- [ ] save saves the entry, adds it to library, returns you to library
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that don't do anything.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
