### ISSUE TITLE
Issue 3: User Can Edit An Entry

### ISSUE THREAD

**Issue by CollinHovey** [CollinHovey/my-shiny-entries#3]
## ⚙️ Feature

> ##### User Can Edit an Entry

## 📐 Plan

> ##### To add a functionality to edit an entry

## 🖼️ Wireframes

> ##### Updated wireframe(s) of what the app should look like when the updates are ready.
![chrome_BNpZvHSusA](https://user-images.githubusercontent.com/102557430/173673621-351907d3-cbc7-4d90-b80c-80ac0b0dc476.png)
![chrome_14NRKytjao](https://user-images.githubusercontent.com/102557430/173673631-8a7714f8-696b-4caf-8e22-ff8ed9d5d9d0.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Add Edit icon to every entry in library
- [ ] Clicking edit icon brings up edit page with entry information filled in
- [ ] hitting cancel returns you back to library page
- [ ] hitting save will return you to the library and change that entry
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that don't do anything.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
