### ISSUE TITLE
Issue 4: User can Mark Entries as Favorites

### ISSUE THREAD

**Issue by CollinHovey** [CollinHovey/my-shiny-entries#4]
## ⚙️ Feature

> ##### User can Mark Entries as Favorites

## 📐 Plan

> ##### Add a favorite icon for users to interact with

## 🖼️ Wireframes
![chrome_yW8xSM3QTy](https://user-images.githubusercontent.com/102557430/173674249-4417270d-7199-465f-aca3-c41635296a87.png)

![chrome_zfa1YFZAba](https://user-images.githubusercontent.com/102557430/173674266-761245eb-a4c0-479f-8727-34c1c9c75aef.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Add heart icon for favorite button
- [ ] Clicking heart icon makes icon a filled heart, and adds it to the favorites tab
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that don't do anything.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
