### ISSUE TITLE
Issue 5: User Can Remove a Shiny Entry

### ISSUE THREAD

**Issue by CollinHovey** [CollinHovey/my-shiny-entries#5]
## ⚙️ Feature

> ##### User Can Remove a Shiny Entry

## 📐 Plan

> ##### add a functional delete button

## 🖼️ Wireframes
![chrome_RXRA3YERkE](https://user-images.githubusercontent.com/102557430/173675095-39a61a4e-cc7b-4ece-a250-026df8f4c910.png)

![chrome_ATsT7366no](https://user-images.githubusercontent.com/102557430/173675103-5a4a14d2-2d6f-4752-a345-957feb704225.png)

> ##### Updated wireframe(s) of what the app should look like when the updates are ready.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Add Delete button to the edit tab
- [ ] On click delete button brings up modal asking to confirm delete
- [ ] when confirmed, entry will be removed from library and favorites if it's there
- [ ] user is returned to library page
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that don't do anything.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
